version : '3.4'

services:
    catalogdb:
        image: mongo

    basketdb:
        image: redis:6.2.13-alpine3.18

    discountdb:
        image: postgres

    catalog.api:
        image: ${DOCKER_REGISTRY-}catalogapi
        build:
            context: .
            dockerfile: services/catalog/catalog.API/Dockerfile

    discount.api:
        image: ${DOCKER_REGISTRY-}discountapi
        build:
            context: .
            dockerfile: services/discount/discount.API/Dockerfile

    portainer:
        image: portainer/portainer-ce

    pgadmin:
        image: dpage/pgadmin4

    basket.api:
        image: ${DOCKER_REGISTRY-}basketapi
        build:
            context: .
            dockerfile: services/basket/basket.API/Dockerfile

    discount.grpc:
        image: ${DOCKER_REGISTRY-}discountgrpc
        build:
            context: .
            dockerfile: services/discount/discount.grpc/Dockerfile

volumes:
    mongo_data: 
    portainer_data:
    postgres_data:
    pgadmin_data:
    